config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  devise_for :users
  resources :groups, shallow: true do
    resources :messages, only: [:index, :create]
  end
  get 'users/search' => 'users#search'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users, through: :group_users
  has_many :messages
  has_many :group_users
  accepts_nested_attributes_for :users
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/massage.rb
class Massage < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  validate :can_not_empty
  mount_uploader :image, ImageUploader

  def can_not_empty
    errors.add(:text, "を入力してください") unless text && image
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 8 }
  has_many :messages
  has_many :groups, through: :group_users
  has_many :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:edit, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @groups = Group.order(created_at: :desc)
  end

  def new
    @group = Group.new
    @members = User.order(created_at: :desc)
    @users = User.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = 'チャットグループが作成されました。'
      redirect_to :root and return
    else
      flash[:alert] = 'グループ名を入力してください。'
      render :new and return
    end
  end

  def edit
    @users = @group.users
  end

  def update
    if @group.update(group_params)
      flash[:notice] = 'チャットグループが更新されました'
      redirect_to :root
    else
      flash[:alert] = 'チャットグループが更新されませんでした'
      render :edit and return
    end
  end

  private
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :group_params
  def index
    @groups = Group.order(created_at: :desc)
    @messages = @group.messages
    @message = Message.new
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      flash[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private
  def group_params
    @group = Group.find(params[:group_id])
  end

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    @users = User.where("name like ?", "%#{search_params[:q]}%").order('name ASC')
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  private
  def search_params
    params.permit(:q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group-form__input', id: 'chat_group_name'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label 'チャットメンバー', class: 'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user-932.chat-group-user.clearfix
            = f.collection_check_boxes :user_ids, User.all, :id, :name do |b|
              = b.label {b.check_box + b.text}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/groups/index.html.haml
.chat
  = render 'layouts/sidebar'
  .chat-main

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, placeholder: 'グループ名を入力してください', class: 'chat-group-form__input', id: 'chat_group_name'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label 'チャットメンバーを追加', class: 'chat-group-form__label'
      .chat-group-form__field--right
        %input#user-search-field.chat-group-form__input{ type: "text", placeholder: "メンバーを追加してください"}
        .chat-group-user__list
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label 'チャットメンバー', id: 'chat_group_チャットメンバー', class: 'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            .chat-group-add-user__name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/layouts/_flash_messages.haml
- flash.each do |key, value|
  = content_tag :div, value, class: "layout-#{key}"

app/views/layouts/_group.html.haml
%ul.chat-groups
  %li.chat-group
    = link_to group_messages_path(group), class: "chat-group__link" do
      %p.chat-group__name= group.name
      %p.chat-group__message= group.messages.first.try(:text)

app/views/layouts/_sidebar.html.haml
.chat-side
  .chat-user.clearfix
    %h5= current_user.name
    .chat-user__actions
      = link_to new_group_path, class: "chat-user__action" do
        %i.fa.fa-pencil-square-o
      = link_to edit_user_registration_path, class: "chat-user__action" do
        %i.fa.fa-cog
  = render partial: 'layouts/group', collection: @groups

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/flash_messages'
    = yield

app/views/messages/_chat_body.html.haml
%li.chat-message
  .chat-message__header.clearfix
    %p.chat-message__name= chat_body.user.name
    %p.chat-message__time= chat_body.created_at.to_s(:published_on)
    - if chat_body.text?
      %p.chat-message__body= chat_body.text
    - if chat_body.image?
      = image_tag(chat_body.image)

app/views/messages/index.html.haml
.chat
  = render 'layouts/sidebar'
  .chat-main
    .chat-header.clearfix
      .chat-header--left
        %h2= @group.name
        .chat-header__users
          %span.chat-header__user= "Member #{@group.users.pluck(:name).join}"
      .chat-header--right
        = link_to 'Edit' ,edit_group_path(@group), class: "chat-header__edit-btn"
    .chat-body
      %ul.chat-messages
        = render partial: 'messages/chat_body', collection: @messages
    .chat-footer
      = form_for [@group, @message], id: 'new_message', html: {class: 'new_message'}, remote: true do |f|
        .chat-footer__body
          = f.text_field :text, placeholder: 'type a message', row: 1, id: 'message_body', class: 'js-form__text-field'
          %label.chat-footer__file
            %i.fa.fa-image
              = f.file_field :image, class: "image_form_button"
        = f.submit 'Sent'